### PR TITLE
Animation

### PR DESCRIPTION
**Pull request by RogierVrooman**

### CODE REVIEW

**Comment by karinvangarderen** [comment]
Looks fine!

**Comment by cmaulany** [comment]
wil het mergen lukken?

**Comment by RogierVrooman** [comment]
Merge was successful, but now travis cannot build successfully. I think it is due to some testing or something. Don't really understand

**Comment by BdeBock** [comment]
Results :
Tests in error: 
  nextPositionStopTest(sem.group47.entity.PlayerTest)
  nextPositionLeftTest(sem.group47.entity.PlayerTest)
  hitFlinchTest(sem.group47.entity.PlayerTest)
  updateTest(sem.group47.entity.PlayerTest)
  hitDeadTest(sem.group47.entity.PlayerTest)
  hitOutOfBoundsTest(sem.group47.entity.PlayerTest)
  nextPositionUpTest(sem.group47.entity.PlayerTest)
  nextPositionRightTest(sem.group47.entity.PlayerTest)
  hitTest(sem.group47.entity.PlayerTest)
  nextPositionFallingTest(sem.group47.entity.PlayerTest)
  testGameUpdate(sem.group47.gamestate.GameStateManagerTest)
  testGameUpdateAndDraw(sem.group47.gamestate.GameStateManagerTest)
Tests run: 29, Failures: 0, Errors: 12, Skipped: 0

Er gaat iets mis met het loggen in de testen. Check de Travis message.

**Comment by RogierVrooman** [comment]
Awesome, travis build is succesfull! The branch can be merged

**Comment by BdeBock** [comment]
Go go merge!

**Pull request merged**
